import type { ClubType } from '@/types';
import type { CompetitionId } from './competitions';

export const CLUBS: ClubType[] = [
  {code: 332, name: 'ALCALA PA', competition: 'FMP', username: 'alcala'},
  {code: 454, name: '50 PROJECT EP', competition: 'FMP', username: '50project'},
  {code: 462, name: 'ADITE PA', competition: 'FMP', username: 'adite'},
  {code: 386, name: 'ALAMEDA OSUNA HP', competition: 'FMP', username: 'alameda'},
  {code: 503, name: 'ALBACETE H.C.', competition: 'FMP', username: 'albacete'},
  {code: 423, name: 'ALCALA HP', competition: 'FMP', username: 'alcalaHP'},
  {code: 399, name: 'ALCOBENDAS HP', competition: 'FMP', username: 'alcobendas'},
  {code: 328, name: 'ALCOBENDAS PA', competition: 'FMP', username: 'alcobendasPA'},
  {code: 398, name: 'ALDOVEA HP', competition: 'FMP', username: 'aldovea'},
  {code: 488, name: 'ALOHA PA', competition: 'FMP', username: 'aloha'},
  {code: 393, name: 'ALUCHE HP', competition: 'FMP', username: 'alucheHP'},
  {code: 331, name: 'ALUCHE PA', competition: 'FMP', username: 'aluchePA'},
  {code: 358, name: 'ARANJUEZ PA', competition: 'FMP', username: 'aranjuez'},
  {code: 368, name: 'ARGANDA PV', competition: 'FMP', username: 'arganda'},
  {code: 341, name: 'ARTISTICO LAS ROZAS PA', competition: 'FMP', username: 'artisticoLR'},
  {code: 460, name: 'ARTIUM PA', competition: 'FMP', username: 'artium'},
  {code: 431, name: 'ASOC. PATIN LINEA ALCALA HL', competition: 'FMP', username: 'asocpatin'},
  {code: 440, name: 'AVILA', competition: 'FMP', username: 'avila'},
  {code: 499, name: 'BECERRIL', competition: 'FMP', username: 'becerril'},
  {code: 345, name: 'BERNABELLA PA', competition: 'FMP', username: 'bernabella'},
  {code: 360, name: 'BERNADETTE PA', competition: 'FMP', username: 'bernadette'},
  {code: 389, name: 'BLACK THUNDERS RD', competition: 'FMP', username: 'blackthunders'},
  {code: 457, name: 'BOADILLA DEL MONTE H.P.', competition: 'FMP', username: 'boadillaHP'},
  {code: 455, name: 'BOADILLA DEL MONTE PA', competition: 'FMP', username: 'boadillaPA'},
  {code: 403, name: 'BOADILLA PATINA HL-PAL-FS-PV', competition: 'FMP', username: 'boadillapatina'},
  {code: 382, name: 'BREZO OSUNA PA', competition: 'FMP', username: 'brezo'},
  {code: 505, name: 'BURDINOLA', competition: 'FMP', username: 'burdinola'},
  {code: 441, name: 'BURGUILLOS', competition: 'FMP', username: 'burguillos'},
  {code: 507, name: 'CALVIA HC', competition: 'FMP', username: 'calvia'},
  {code: 434, name: 'CASAR HP', competition: 'FMP', username: 'casar'},
  {code: 361, name: 'CASTILLA PA', competition: 'FMP', username: 'castilla'},
  {code: 477, name: 'CEM INLINE', competition: 'FMP', username: 'cem'},
  {code: 426, name: 'CIUDAD PATINA HL', competition: 'FMP', username: 'ciudadpatina'},
  {code: 320, name: 'CLUB DE CAMPO VILLA DE MADRID PA', competition: 'FMP', username: 'clubcampo'},
  {code: 492, name: 'COCENTAINA', competition: 'FMP', username: 'cocentaina'},
  {code: 357, name: 'COLMENAR VIEJO PA', competition: 'FMP', username: 'colmenar'},
  {code: 333, name: 'COSLADA PA Y HP', competition: 'FMP', username: 'coslada'},
  {code: 448, name: 'CP ALCODIAM', competition: 'FMP', username: 'alcodiam'},
  {code: 449, name: 'CP CAJAR', competition: 'FMP', username: 'cajar'},
  {code: 450, name: 'CP IRLANDESAS', competition: 'FMP', username: 'irlandesas'},
  {code: 496, name: 'CPL GALAPAGAR NORK VIKINGS', competition: 'FMP', username: 'galapagarvikings'},
  {code: 451, name: 'CPP RASPEIG', competition: 'FMP', username: 'raspeig'},
  {code: 355, name: 'DAGANZO PA', competition: 'FMP', username: 'daganzo'},
  {code: 446, name: 'DEL PATIN EP', competition: 'FMP', username: 'delpatin'},
  {code: 469, name: 'DOCTOR PATIN HP', competition: 'FMP', username: 'doctorpatinHP'},
  {code: 356, name: 'DOCTOR PATIN PA-PAL', competition: 'FMP', username: 'doctorpatinPA'},
  {code: 344, name: 'EL MEJOR PATIN PA', competition: 'FMP', username: 'mejorpatin'},
  {code: 484, name: 'EL VALLE', competition: 'FMP', username: 'elvalle'},
  {code: 453, name: 'ENLINEA PATINA FS', competition: 'FMP', username: 'enlinea'},
  {code: 497, name: 'ENTABLA SK', competition: 'FMP', username: 'entabla'},
  {code: 475, name: 'FAST ROLLER MADRID PV', competition: 'FMP', username: 'fastroller'},
  {code: 330, name: 'FMP', competition: 'FMP', username: 'fmp'},
  {code: 481, name: 'FREESTYLE MADRID', competition: 'FMP', username: 'freestyle'},
  {code: 493, name: 'FUENGIROLA', competition: 'FMP', username: 'fuengirola'},
  {code: 346, name: 'FUENLABRADA PA Y FS', competition: 'FMP', username: 'fuenlabrada'},
  {code: 506, name: 'FUENLABRADA ROLLER DERBY', competition: 'FMP', username: 'fuenlabradaRD'},
  {code: 459, name: 'GIROS PA', competition: 'FMP', username: 'giros'},
  {code: 425, name: 'GREDOS SAN DIEGO HP', competition: 'FMP', username: 'gredosHP'},
  {code: 326, name: 'GREDOS SAN DIEGO PA', competition: 'FMP', username: 'gredosPA'},
  {code: 396, name: 'H.P. MAJADAHONDA HP', competition: 'FMP', username: 'majadahondaHP'},
  {code: 395, name: 'HOCKEY RIVAS LAS LAGUNAS HP', competition: 'FMP', username: 'rivaslagunas'},
  {code: 438, name: 'IMPULSO URBANO HL', competition: 'FMP', username: 'impulso'},
  {code: 372, name: 'IN-GRAVITY PV-FS', competition: 'FMP', username: 'ingravity'},
  {code: 463, name: 'INLINE MADRID FS-PV-EP-RF', competition: 'FMP', username: 'inlinemadrid'},
  {code: 466, name: 'IWIAS F&A EP', competition: 'FMP', username: 'iwias'},
  {code: 366, name: 'LA DEHESA PA', competition: 'FMP', username: 'ladehsa'},
  {code: 352, name: 'LA VIDA SOBRE RUEDAS PA-PAL', competition: 'FMP', username: 'lavidasobreruedas'},
  {code: 420, name: 'LAS ROZAS HL', competition: 'FMP', username: 'lasrozasHL'},
  {code: 400, name: 'LAS ROZAS HP', competition: 'FMP', username: 'lasrozasHP'},
  {code: 429, name: 'LOBOS CASTILLA HL', competition: 'FMP', username: 'loboscastilla'},
  {code: 504, name: 'MAD RAMPS', competition: 'FMP', username: 'madramps'},
  {code: 349, name: 'MADRID SOMONTES PA', competition: 'FMP', username: 'madridSomontes'},
  {code: 433, name: 'MADRIDERS', competition: 'FMP', username: 'madriders'},
  {code: 375, name: 'MADRIDPATINA', competition: 'FMP', username: 'madridpatina'},
  {code: 338, name: 'MAJADAHONDA PA', competition: 'FMP', username: 'majadahondaPA'},
  {code: 412, name: 'MAMUTS HOCKEY', competition: 'FMP', username: 'mamuts'},
  {code: 461, name: 'MDLS - MIRAFLORES PA', competition: 'FMP', username: 'miraflores'},
  {code: 436, name: 'MIL RUEDAS PA', competition: 'FMP', username: 'milruedas'},
  {code: 491, name: 'MOLINA SPORT', competition: 'FMP', username: 'molina'},
  {code: 342, name: 'MORATALAZ PA', competition: 'FMP', username: 'moratalaz'},
  {code: 359, name: 'MOSTOLES 08 PA', competition: 'FMP', username: 'mostoles08'},
  {code: 335, name: 'MOSTOLES PA', competition: 'FMP', username: 'mostoles'},
  {code: 343, name: 'NERON PA', competition: 'FMP', username: 'neron'},
  {code: 476, name: 'ONSKATES FS', competition: 'FMP', username: 'onskates'},
  {code: 413, name: 'PARLA EP', competition: 'FMP', username: 'parla'},
  {code: 334, name: 'PATIN ALCORCON HP Y PA', competition: 'FMP', username: 'alcorcon'},
  {code: 371, name: 'PATIN DE ORO', competition: 'FMP', username: 'patindeoro'},
  {code: 473, name: 'PATIN PARQUE LISBOA PA Y EP', competition: 'FMP', username: 'parquelisboa'},
  {code: 362, name: 'PATIN TEJAR DE SOMONTES', competition: 'FMP', username: 'tejarsomontes'},
  {code: 354, name: 'PATINA LAS ROZAS FS-PAL', competition: 'FMP', username: 'patinalasrozas'},
  {code: 489, name: 'PATINAJE AL3', competition: 'FMP', username: 'patinajeal3'},
  {code: 480, name: 'PATINAJE FLIP PA', competition: 'FMP', username: 'patinajeflip'},
  {code: 406, name: 'PATINAJE LINEA MADRID', competition: 'FMP', username: 'patinajelineamadrid'},
  {code: 465, name: 'PEDREZUELA', competition: 'FMP', username: 'pedrezuela'},
  {code: 421, name: 'PINGUINOS', competition: 'FMP', username: 'pinguinos'},
  {code: 410, name: 'PUMAS DEL NORTE PAL-HL', competition: 'FMP', username: 'pumas'},
  {code: 397, name: 'RETAMAR', competition: 'FMP', username: 'retamar'},
  {code: 464, name: 'ROLLART SANSE PA', competition: 'FMP', username: 'rollart'},
  {code: 479, name: 'ROLLER CENTER PA Y FS', competition: 'FMP', username: 'rollercenter'},
  {code: 388, name: 'ROLLER DERBY MADRID', competition: 'FMP', username: 'rollerderby'},
  {code: 445, name: 'ROLLER STYLE FS', competition: 'FMP', username: 'rollerstyle'},
  {code: 444, name: "ROLLER'S STARS PAL-PA", competition: 'FMP', username: 'rollersstars'},
  {code: 414, name: 'ROLLERGREEN', competition: 'FMP', username: 'rollergreen'},
  {code: 502, name: 'ROLLERMANIACOS', competition: 'FMP', username: 'rollermaniacos'},
  {code: 418, name: 'ROLLING NORTE EP', competition: 'FMP', username: 'rollingnorte'},
  {code: 495, name: 'ROLLYBEARS PARLA HL', competition: 'FMP', username: 'rollybears'},
  {code: 351, name: 'ROULEMENT', competition: 'FMP', username: 'roulement'},
  {code: 483, name: 'RUEDA MADRID', competition: 'FMP', username: 'ruedamadrid'},
  {code: 474, name: 'SALAMANCA H.C.', competition: 'FMP', username: 'salamanca'},
  {code: 427, name: 'SAMURAI HL-PA-EP', competition: 'FMP', username: 'samurai'},
  {code: 365, name: 'SAN AGUSTIN', competition: 'FMP', username: 'sanagustin'},
  {code: 472, name: 'SAN FERNANDO HENARES PA', competition: 'FMP', username: 'sanfernando'},
  {code: 470, name: 'SANSE HOCKEY HP', competition: 'FMP', username: 'sanse'},
  {code: 486, name: 'SILVER PA', competition: 'FMP', username: 'silver'},
  {code: 500, name: 'SKATE POZUELO', competition: 'FMP', username: 'skatepozuelo'},
  {code: 501, name: 'SKATEFUN', competition: 'FMP', username: 'skatefun'},
  {code: 384, name: 'SLIDERS', competition: 'FMP', username: 'sliders'},
  {code: 376, name: 'SOBRE8RUEDAS', competition: 'FMP', username: 'sobre8ruedas'},
  {code: 383, name: 'SOBRERUEDAMADRID', competition: 'FMP', username: 'sobreruedamadrid'},
  {code: 402, name: 'SPEED WHEELS', competition: 'FMP', username: 'speedwheels'},
  {code: 374, name: 'SPORTING DE VALLECAS FS-PAL', competition: 'FMP', username: 'sportingvallecas'},
  {code: 329, name: 'STA. Mª DEL PILAR HP Y PA', competition: 'FMP', username: 'pilar'},
  {code: 428, name: 'STA. Mª LA BLANCA', competition: 'FMP', username: 'lablanca'},
  {code: 407, name: 'TIGRES DE ARANJUEZ', competition: 'FMP', username: 'tigres'},
  {code: 411, name: 'TISO PATIN', competition: 'FMP', username: 'tiso'},
  {code: 353, name: 'TORRELODONES', competition: 'FMP', username: 'torrelodones'},
  {code: 387, name: 'TRES CANTOS HL', competition: 'FMP', username: 'trescantosHL'},
  {code: 424, name: 'TRES CANTOS HP', competition: 'FMP', username: 'trescantosHP'},
  {code: 347, name: 'TRES CANTOS P.A.', competition: 'FMP', username: 'trescantosPA'},
  {code: 373, name: 'TRES60', competition: 'FMP', username: 'tres60'},
  {code: 490, name: 'TROYANOS VILLARROBLEDO', competition: 'FMP', username: 'troyanos1'},
  {code: 498, name: 'TROYANOS VILLARROBLEDO', competition: 'FMP', username: 'troyanos2'},
  {code: 458, name: 'TRS MADRID', competition: 'FMP', username: 'trsmadrid'},
  {code: 494, name: 'UNIQUE PA', competition: 'FMP', username: 'unique'},
  {code: 340, name: 'UP RIVAS', competition: 'FMP', username: 'uprivas'},
  {code: 485, name: 'VALENTIA HP', competition: 'FMP', username: 'valentia'},
  {code: 339, name: 'VALLEHERMOSO', competition: 'FMP', username: 'vallehermoso'},
  {code: 370, name: 'VALLEKAS', competition: 'FMP', username: 'vallekas'},
  {code: 508, name: 'VALLMONT PA', competition: 'FMP', username: 'vallmont'},
  {code: 337, name: 'VELILLA', competition: 'FMP', username: 'velilla'},
  {code: 378, name: 'VELOCIDAD RIVAS PV-FS-EP', competition: 'FMP', username: 'velocidadrivas'},
  {code: 437, name: 'VETTONIA', competition: 'FMP', username: 'vettonia'},
  {code: 322, name: 'VILLANUEVA DEL PARDILLO', competition: 'FMP', username: 'villanuevapardillo'},
  {code: 435, name: 'VILLANUEVA PATINA EP', competition: 'FMP', username: 'villanuevapatina'},
  {code: 394, name: 'VIRGEN DE EUROPA', competition: 'FMP', username: 'virgendeuropa'},
];

export const CLUBS_MAP: Record<number, ClubType> = CLUBS.reduce((acc, club) => {
  acc[club.code] = club;
  return acc;
}, {} as Record<number, ClubType>);

export function getClubName(code: number): string {
  const club = CLUBS_MAP[code];
  return club ? club.name : 'Club no encontrado';
}

export function getClubsByCompetition(competition: CompetitionId): ClubType[] {
  return CLUBS.filter((c) => c.competition === competition);
}
